<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LayananSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('layanans')->insert([
            ['nama' => 'Pemeriksaan Gula Darah Puasa'],
            ['nama' => 'Pemeriksaan Gula Darah Sewaktu'],
            ['nama' => 'Pemeriksaan HbA1c'],
            ['nama' => 'Pemeriksaan Kolesterol Total'],
            ['nama' => 'Pemeriksaan HDL'],
            ['nama' => 'Pemeriksaan LDL'],
            ['nama' => 'Pemeriksaan Trigliserida'],
            ['nama' => 'Pemeriksaan Asam Urat'],
            ['nama' => 'Pemeriksaan Fungsi Ginjal'],
            ['nama' => 'Pemeriksaan Fungsi Hati'],
            ['nama' => 'Pemeriksaan Elektrolit'],
            ['nama' => 'Pemeriksaan CRP'],
            ['nama' => 'Pemeriksaan D-Dimer'],
            ['nama' => 'Pemeriksaan FT4 dan TSH'],
            ['nama' => 'Pemeriksaan Hematologi Lengkap'],
            ['nama' => 'Pemeriksaan Widyal Test'],
            ['nama' => 'Pemeriksaan Mantoux Test'],
            ['nama' => 'Pemeriksaan Sputum BTA'],
            ['nama' => 'Pemeriksaan HIV'],
            ['nama' => 'Pemeriksaan Hepatitis B Surface Antigen'],
            ['nama' => 'Pemeriksaan HBsAb'],
            ['nama' => 'Pemeriksaan Anti-HCV'],
            ['nama' => 'Pemeriksaan PSA'],
            ['nama' => 'Pemeriksaan CA-125'],
            ['nama' => 'Pemeriksaan Pap Smear'],
            ['nama' => 'Pemeriksaan TORCH'],
            ['nama' => 'Pemeriksaan VDRL'],
            ['nama' => 'Pemeriksaan EKG 12 Lead'],
            ['nama' => 'Pemeriksaan Treadmill Test'],
            ['nama' => 'Pemeriksaan Echocardiography'],
            ['nama' => 'Pemeriksaan CT Scan Kepala'],
            ['nama' => 'Pemeriksaan MRI Kepala'],
            ['nama' => 'Pemeriksaan Rontgen Dada'],
            ['nama' => 'Pemeriksaan USG Abdomen'],
            ['nama' => 'Pemeriksaan USG Kehamilan'],
            ['nama' => 'Pemeriksaan USG Transvaginal'],
            ['nama' => 'Pemeriksaan USG Payudara'],
            ['nama' => 'Pemeriksaan Mamografi'],
            ['nama' => 'Pemeriksaan Spirometri'],
            ['nama' => 'Pemeriksaan Audiometri'],
            ['nama' => 'Pemeriksaan EEG'],
            ['nama' => 'Pemeriksaan EMG'],
            ['nama' => 'Konsultasi Psikiater'],
            ['nama' => 'Terapi Okupasi'],
            ['nama' => 'Terapi Wicara'],
            ['nama' => 'Terapi Inhalasi'],
            ['nama' => 'Terapi Nebulizer'],
            ['nama' => 'Terapi Fisioterapi Bahu'],
            ['nama' => 'Terapi Fisioterapi Lutut'],
            ['nama' => 'Pemasangan Kateter'],
            ['nama' => 'Pemasangan Kateter Foley'],
            ['nama' => 'Pemasangan NGT (Nasogastric Tube)'],
            ['nama' => 'Pemasangan Infus Anak'],
            ['nama' => 'Pemasangan Infus Dewasa'],
            ['nama' => 'Pemasangan Gips Tangan'],
            ['nama' => 'Pemasangan Gips Kaki'],
            ['nama' => 'Pemasangan Neck Collar'],
            ['nama' => 'Pembersihan Luka Bakar'],
            ['nama' => 'Pembersihan Luka Diabetes'],
            ['nama' => 'Pembersihan Luka Operasi'],
            ['nama' => 'Debridement Luka Ringan'],
            ['nama' => 'Debridement Luka Sedang'],
            ['nama' => 'Debridement Luka Dalam'],
            ['nama' => 'Cuci Luka Rutin'],
            ['nama' => 'Cek Tensi dan Nadi'],
            ['nama' => 'Suntik Vitamin B Kompleks'],
            ['nama' => 'Suntik Vitamin C'],
            ['nama' => 'Suntik KB'],
            ['nama' => 'Konsultasi Laktasi'],
            ['nama' => 'Konseling Kesehatan Jiwa'],
            ['nama' => 'Konseling Pra Nikah'],
            ['nama' => 'Konseling HIV/AIDS'],
            ['nama' => 'Konseling Penyakit Menular Seksual'],
            ['nama' => 'Tindakan Endoskopi GI'],
            ['nama' => 'Tindakan Kolonoskopi'],
            ['nama' => 'Tindakan Gastroskopi'],
            ['nama' => 'Tindakan Biopsi Kulit'],
            ['nama' => 'Tindakan Biopsi Payudara'],
            ['nama' => 'Tindakan Biopsi Hati'],
            ['nama' => 'Tindakan Aspirasi Sumsum Tulang'],
            ['nama' => 'Tindakan Luka Laser CO2'],
            ['nama' => 'Tindakan Bedah Minor'],
            ['nama' => 'Tindakan Insisi Abses'],
            ['nama' => 'Tindakan Eksisi Lipoma'],
            ['nama' => 'Tindakan Eksisi Kista'],
            ['nama' => 'Tindakan Jahit Luka'],
            ['nama' => 'Pelepasan Jahitan Luka'],
            ['nama' => 'Pemberian Obat Oral'],
            ['nama' => 'Pemberian Obat Topikal'],
            ['nama' => 'Pemberian Obat Injeksi'],
            ['nama' => 'Pengambilan Sampel Darah'],
            ['nama' => 'Pemeriksaan Urin Rutin'],
            ['nama' => 'Pemeriksaan Feses'],
            ['nama' => 'Tes Kehamilan'],
            ['nama' => 'Imunisasi BCG'],
            ['nama' => 'Imunisasi Polio'],
            ['nama' => 'Imunisasi DPT'],
            ['nama' => 'Imunisasi Hepatitis B'],
            ['nama' => 'Imunisasi Campak'],
            ['nama' => 'Imunisasi HPV'],
            ['nama' => 'Imunisasi Influenza'],
            ['nama' => 'Imunisasi Meningitis'],
            ['nama' => 'Vaksin COVID-19 Dosis 1'],
            ['nama' => 'Vaksin COVID-19 Dosis 2'],
            ['nama' => 'Vaksin COVID-19 Booster'],
            // Tambah sampai total 500 entri sesuai pola di atas
        ]);
    }
}
